Repository CoworkCode/coworking-space, pull requests merged in 2024-04, with the labels that each got.

#2 feat : hero section HTML작성
  index.html
  resources/css/web.css
Labels: 💡 Feature, 🤝 Pair Programming

#3 fix: PULL_REQUEST_TEMPLATE.yml - pull request 템플릿 경로 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :hammer_and_wrench: fix, :briefcase: rename

#4 Feat/hero section
  index.html
  resources/css/web.css
Labels: 💡 Feature

#5 feat: social proof구현
  index.html
  resources/css/web.css
  resources/images/Row.svg
Labels: 💡 Feature

#7 feat: features Section 구현 완료
  index.html
  resources/css/web.css
  resources/images/CreditCardIcon.svg
  resources/images/PlanetIcon.svg
  resources/images/UserList.svg
Labels: 💡 Feature

#8 fix : index.html hero-article-text 수정
  index.html
  resources/css/web.css
  resources/images/circle.svg
Labels: :hammer_and_wrench: fix

#9 fix: web.css - Features 내용물 Column 정렬으로 수정
  resources/css/web.css
Labels: :hammer_and_wrench: fix

#12 fix: 가독성 향상을 위해 body location이 중앙으로 모이도록 수정
  index.html
  resources/css/web.css
Labels: :hammer_and_wrench: fix

#20 docs: Readme.md - 홈페이지 바로 가기 링크 및 컨벤션 차트화
  README.md
Labels: :memo: docs

#24 Feature/statistics page
  index.html
  resources/css/web.css
  resources/images/Placeholder _ Image3.svg
  resources/images/row-blue-ball.svg
  resources/images/row-green-ball.svg
  resources/images/row-orange-ball.svg
  resources/images/row-pink-ball.svg
Labels: 💡 Feature

#26 fix : web.css statistic CSS 오류 해결
  resources/css/web.css
Labels: :hammer_and_wrench: fix

#27 fix : pinkball 이상한 위치에 공 생기는 현상 수정
  index.html
  resources/css/web.css
Labels: :hammer_and_wrench: fix

#28 feat: FAQ Section 구현 완료
  index.html
  resources/css/web.css
  resources/images/CaretCircleDown.svg
  resources/images/CaretCircleUp.svg
Labels: 💡 Feature

#30 refactor : 일관성을 위해 버튼 클래스 통일
  index.html
  resources/css/web.css
Labels: :recycle: refactor

#31 feat - blog section 구현 완료
  index.html
  resources/css/web.css
  resources/images/Vector3.svg
  resources/images/blog-rect.svg
  resources/images/blog1.svg
  resources/images/blog2.svg
  resources/images/blog3.svg
Labels: 💡 Feature

#32 feat : CTA Section 구현 완료
  index.html
  resources/css/web.css
  resources/images/Rectangle 4.svg
Labels: 💡 Feature

#33 feat : footer 구현 완료
  index.html
  resources/css/web.css
Labels: 💡 Feature, 🤝 Pair Programming

#35 fix : blog button
  index.html
  resources/css/web.css
Labels: :hammer_and_wrench: fix

#36 fix index.html - button html 긴급 수정
  index.html
Labels: :hammer_and_wrench: fix
